sonar.projectKey=VOTRE_PROJECT_KEY
sonar.organization=VOTRE_ORGANISATION

# Informations du projet
sonar.projectName=Qualimetrie TP - Cert Score API
sonar.projectVersion=1.0

# Source et tests
sonar.sources=src,app.js
sonar.tests=src
sonar.test.inclusions=**/*.test.js
sonar.exclusions=**/node_modules/**,**/coverage/**

# Rapport de couverture Jest (généré par jest --coverage)
sonar.javascript.lcov.reportPaths=coverage/lcov.info

# Encodage
sonar.sourceEncoding=UTF-8
